/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch APU Material Design 3 palette
        'primary': '#670024',
        'on-primary': '#ffffff',
        'primary-container': '#8a1538',
        'on-primary-container': '#ff97a8',
        'primary-fixed': '#ffd9dd',
        'primary-fixed-dim': '#ffb2bd',
        'on-primary-fixed': '#400013',
        'on-primary-fixed-variant': '#8a1538',
        'inverse-primary': '#ffb2bd',
        'secondary': '#5d5e61',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2e2e5',
        'on-secondary-container': '#636467',
        'secondary-fixed': '#e2e2e5',
        'secondary-fixed-dim': '#c6c6c9',
        'on-secondary-fixed': '#1a1c1e',
        'on-secondary-fixed-variant': '#454749',
        'tertiary': '#003921',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#005232',
        'on-tertiary-container': '#7fc49b',
        'tertiary-fixed': '#abf2c6',
        'tertiary-fixed-dim': '#90d5ab',
        'on-tertiary-fixed': '#002111',
        'on-tertiary-fixed-variant': '#005232',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#f8f9fa',
        'on-surface': '#191c1d',
        'on-surface-variant': '#574144',
        'surface-variant': '#e1e3e4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-tint': '#aa304f',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'outline': '#8a7174',
        'outline-variant': '#debfc2',
        'background': '#f8f9fa',
        'on-background': '#191c1d',
        // Legacy aliases
        'navy': '#191c1d',
        'apu-crimson': '#670024',
        'apuBlue': '#670024',
        'crimson-dark': '#8a1538',
        'mist': '#f8f9fa',
        'line': '#debfc2',
        'graphite': '#574144',
        'paper': '#ffffff',
        'gold': '#B79A57'
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
        heading: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif']
      },
      fontSize: {
        'display': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }]
      },
      spacing: {
        'margin-desktop': '48px',
        'gutter': '24px',
        'container-max-width': '1280px',
        'stack-sm': '8px',
        'stack-lg': '32px',
        'margin-mobile': '16px',
        'stack-md': '16px',
        'base': '4px'
      },
      boxShadow: {
        soft: '0 12px 28px rgba(17, 17, 17, 0.08)',
        card: '0 4px 12px rgba(0, 0, 0, 0.04)',
        'card-hover': '0 8px 24px rgba(0, 0, 0, 0.08)'
      }
    }
  },
  plugins: []
};
